language: node_js

script: npm run build

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_KEY"
  app: graphql-fake-api
  on:
    branch: master
    repo: Webd01/GraphQL-API
  skip_cleanup: true